CREATE TABLE Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    bday integer NOT NULL
);

CREATE TABLE Book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    author varchar(100) NOT NULL,
    year integer NOT NULL,
    person_id int REFERENCES Person(id) ON DELETE SET NULL,
    expire_date timestamp
);